// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ack.proto

package com.zj.protobuf;
public final class Ack {
  private Ack() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AckMsgOrBuilder extends
          // @@protoc_insertion_point(interface_extends:AckMsg)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.AckMsg.Module fromModule = 3;</code>
     * @return The enum numeric value on the wire for fromModule.
     */
    int getFromModuleValue();
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.AckMsg.Module fromModule = 3;</code>
     * @return The fromModule.
     */
    Ack.AckMsg.Module getFromModule();

    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromUser = 4;</code>
     * @return The fromUser.
     */
    java.lang.String getFromUser();
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromUser = 4;</code>
     * @return The bytes for fromUser.
     */
    com.google.protobuf.ByteString
    getFromUserBytes();

    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destUser = 5;</code>
     * @return The destUser.
     */
    java.lang.String getDestUser();
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destUser = 5;</code>
     * @return The bytes for destUser.
     */
    com.google.protobuf.ByteString
    getDestUserBytes();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.AckMsg.MsgType msgType = 7;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.AckMsg.MsgType msgType = 7;</code>
     * @return The msgType.
     */
    Ack.AckMsg.MsgType getMsgType();

    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>int64 ackMsgId = 8;</code>
     * @return The ackMsgId.
     */
    long getAckMsgId();
  }
  /**
   * Protobuf type {@code AckMsg}
   */
  public static final class AckMsg extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:AckMsg)
          AckMsgOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use AckMsg.newBuilder() to construct.
    private AckMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckMsg() {
      fromModule_ = 0;
      fromUser_ = "";
      destUser_ = "";
      msgType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new AckMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AckMsg(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              fromModule_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fromUser_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              destUser_ = s;
              break;
            }
            case 48: {

              createTime_ = input.readInt64();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 64: {

              ackMsgId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Ack.internal_static_AckMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Ack.internal_static_AckMsg_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      Ack.AckMsg.class, Ack.AckMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code AckMsg.Module}
     */
    public enum Module
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVER = 0;</code>
       */
      SERVER(0),
      /**
       * <code>TRANSFER = 1;</code>
       */
      TRANSFER(1),
      /**
       * <code>CLIENT = 2;</code>
       */
      CLIENT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SERVER = 0;</code>
       */
      public static final int SERVER_VALUE = 0;
      /**
       * <code>TRANSFER = 1;</code>
       */
      public static final int TRANSFER_VALUE = 1;
      /**
       * <code>CLIENT = 2;</code>
       */
      public static final int CLIENT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
                  "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Module valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Module forNumber(int value) {
        switch (value) {
          case 0: return SERVER;
          case 1: return TRANSFER;
          case 2: return CLIENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Module>
      internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
              Module> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Module>() {
                public Module findValueByNumber(int number) {
                  return Module.forNumber(number);
                }
              };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
                  "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return Ack.AckMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Module[] VALUES = values();

      public static Module valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Module(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:AckMsg.Module)
    }

    /**
     * Protobuf enum {@code AckMsg.MsgType}
     */
    public enum MsgType
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DELIVERED = 0;</code>
       */
      DELIVERED(0),
      /**
       * <code>READ = 1;</code>
       */
      READ(1),
      /**
       * <code>FRIENDAGREE = 2;</code>
       */
      FRIENDAGREE(2),
      /**
       * <code>FRIENDDELETE = 3;</code>
       */
      FRIENDDELETE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DELIVERED = 0;</code>
       */
      public static final int DELIVERED_VALUE = 0;
      /**
       * <code>READ = 1;</code>
       */
      public static final int READ_VALUE = 1;
      /**
       * <code>FRIENDAGREE = 2;</code>
       */
      public static final int FRIENDAGREE_VALUE = 2;
      /**
       * <code>FRIENDDELETE = 3;</code>
       */
      public static final int FRIENDDELETE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
                  "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return DELIVERED;
          case 1: return READ;
          case 2: return FRIENDAGREE;
          case 3: return FRIENDDELETE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
      internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
              MsgType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
                public MsgType findValueByNumber(int number) {
                  return MsgType.forNumber(number);
                }
              };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
                  "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return Ack.AckMsg.getDescriptor().getEnumTypes().get(1);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:AckMsg.MsgType)
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int FROMMODULE_FIELD_NUMBER = 3;
    private int fromModule_;
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.AckMsg.Module fromModule = 3;</code>
     * @return The enum numeric value on the wire for fromModule.
     */
    @java.lang.Override public int getFromModuleValue() {
      return fromModule_;
    }
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.AckMsg.Module fromModule = 3;</code>
     * @return The fromModule.
     */
    @java.lang.Override public Ack.AckMsg.Module getFromModule() {
      @SuppressWarnings("deprecation")
      Ack.AckMsg.Module result = Ack.AckMsg.Module.valueOf(fromModule_);
      return result == null ? Ack.AckMsg.Module.UNRECOGNIZED : result;
    }

    public static final int FROMUSER_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromUser_;
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromUser = 4;</code>
     * @return The fromUser.
     */
    @java.lang.Override
    public java.lang.String getFromUser() {
      java.lang.Object ref = fromUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromUser = 4;</code>
     * @return The bytes for fromUser.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getFromUserBytes() {
      java.lang.Object ref = fromUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        fromUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTUSER_FIELD_NUMBER = 5;
    private volatile java.lang.Object destUser_;
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destUser = 5;</code>
     * @return The destUser.
     */
    @java.lang.Override
    public java.lang.String getDestUser() {
      java.lang.Object ref = destUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destUser = 5;</code>
     * @return The bytes for destUser.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDestUserBytes() {
      java.lang.Object ref = destUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        destUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 7;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.AckMsg.MsgType msgType = 7;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.AckMsg.MsgType msgType = 7;</code>
     * @return The msgType.
     */
    @java.lang.Override public Ack.AckMsg.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      Ack.AckMsg.MsgType result = Ack.AckMsg.MsgType.valueOf(msgType_);
      return result == null ? Ack.AckMsg.MsgType.UNRECOGNIZED : result;
    }

    public static final int ACKMSGID_FIELD_NUMBER = 8;
    private long ackMsgId_;
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>int64 ackMsgId = 8;</code>
     * @return The ackMsgId.
     */
    @java.lang.Override
    public long getAckMsgId() {
      return ackMsgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (fromModule_ != Ack.AckMsg.Module.SERVER.getNumber()) {
        output.writeEnum(3, fromModule_);
      }
      if (!getFromUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromUser_);
      }
      if (!getDestUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, destUser_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(6, createTime_);
      }
      if (msgType_ != Ack.AckMsg.MsgType.DELIVERED.getNumber()) {
        output.writeEnum(7, msgType_);
      }
      if (ackMsgId_ != 0L) {
        output.writeInt64(8, ackMsgId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, version_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(2, id_);
      }
      if (fromModule_ != Ack.AckMsg.Module.SERVER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(3, fromModule_);
      }
      if (!getFromUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromUser_);
      }
      if (!getDestUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, destUser_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(6, createTime_);
      }
      if (msgType_ != Ack.AckMsg.MsgType.DELIVERED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(7, msgType_);
      }
      if (ackMsgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(8, ackMsgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof Ack.AckMsg)) {
        return super.equals(obj);
      }
      Ack.AckMsg other = (Ack.AckMsg) obj;

      if (getVersion()
              != other.getVersion()) return false;
      if (getId()
              != other.getId()) return false;
      if (fromModule_ != other.fromModule_) return false;
      if (!getFromUser()
              .equals(other.getFromUser())) return false;
      if (!getDestUser()
              .equals(other.getDestUser())) return false;
      if (getCreateTime()
              != other.getCreateTime()) return false;
      if (msgType_ != other.msgType_) return false;
      if (getAckMsgId()
              != other.getAckMsgId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getId());
      hash = (37 * hash) + FROMMODULE_FIELD_NUMBER;
      hash = (53 * hash) + fromModule_;
      hash = (37 * hash) + FROMUSER_FIELD_NUMBER;
      hash = (53 * hash) + getFromUser().hashCode();
      hash = (37 * hash) + DESTUSER_FIELD_NUMBER;
      hash = (53 * hash) + getDestUser().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getCreateTime());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + ACKMSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getAckMsgId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Ack.AckMsg parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ack.AckMsg parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ack.AckMsg parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ack.AckMsg parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ack.AckMsg parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ack.AckMsg parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ack.AckMsg parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static Ack.AckMsg parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ack.AckMsg parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static Ack.AckMsg parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ack.AckMsg parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static Ack.AckMsg parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Ack.AckMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AckMsg}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:AckMsg)
            Ack.AckMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return Ack.internal_static_AckMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return Ack.internal_static_AckMsg_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Ack.AckMsg.class, Ack.AckMsg.Builder.class);
      }

      // Construct using Ack.AckMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        id_ = 0L;

        fromModule_ = 0;

        fromUser_ = "";

        destUser_ = "";

        createTime_ = 0L;

        msgType_ = 0;

        ackMsgId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return Ack.internal_static_AckMsg_descriptor;
      }

      @java.lang.Override
      public Ack.AckMsg getDefaultInstanceForType() {
        return Ack.AckMsg.getDefaultInstance();
      }

      @java.lang.Override
      public Ack.AckMsg build() {
        Ack.AckMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Ack.AckMsg buildPartial() {
        Ack.AckMsg result = new Ack.AckMsg(this);
        result.version_ = version_;
        result.id_ = id_;
        result.fromModule_ = fromModule_;
        result.fromUser_ = fromUser_;
        result.destUser_ = destUser_;
        result.createTime_ = createTime_;
        result.msgType_ = msgType_;
        result.ackMsgId_ = ackMsgId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Ack.AckMsg) {
          return mergeFrom((Ack.AckMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Ack.AckMsg other) {
        if (other == Ack.AckMsg.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.fromModule_ != 0) {
          setFromModuleValue(other.getFromModuleValue());
        }
        if (!other.getFromUser().isEmpty()) {
          fromUser_ = other.fromUser_;
          onChanged();
        }
        if (!other.getDestUser().isEmpty()) {
          destUser_ = other.destUser_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.getAckMsgId() != 0L) {
          setAckMsgId(other.getAckMsgId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        Ack.AckMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Ack.AckMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>int32 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>int32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {

        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>int32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {

        version_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int64 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int64 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int64 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private int fromModule_ = 0;
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.AckMsg.Module fromModule = 3;</code>
       * @return The enum numeric value on the wire for fromModule.
       */
      @java.lang.Override public int getFromModuleValue() {
        return fromModule_;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.AckMsg.Module fromModule = 3;</code>
       * @param value The enum numeric value on the wire for fromModule to set.
       * @return This builder for chaining.
       */
      public Builder setFromModuleValue(int value) {

        fromModule_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.AckMsg.Module fromModule = 3;</code>
       * @return The fromModule.
       */
      @java.lang.Override
      public Ack.AckMsg.Module getFromModule() {
        @SuppressWarnings("deprecation")
        Ack.AckMsg.Module result = Ack.AckMsg.Module.valueOf(fromModule_);
        return result == null ? Ack.AckMsg.Module.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.AckMsg.Module fromModule = 3;</code>
       * @param value The fromModule to set.
       * @return This builder for chaining.
       */
      public Builder setFromModule(Ack.AckMsg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }

        fromModule_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.AckMsg.Module fromModule = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromModule() {

        fromModule_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fromUser_ = "";
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @return The fromUser.
       */
      public java.lang.String getFromUser() {
        java.lang.Object ref = fromUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @return The bytes for fromUser.
       */
      public com.google.protobuf.ByteString
      getFromUserBytes() {
        java.lang.Object ref = fromUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          fromUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @param value The fromUser to set.
       * @return This builder for chaining.
       */
      public Builder setFromUser(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        fromUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUser() {

        fromUser_ = getDefaultInstance().getFromUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @param value The bytes for fromUser to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        fromUser_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destUser_ = "";
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @return The destUser.
       */
      public java.lang.String getDestUser() {
        java.lang.Object ref = destUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @return The bytes for destUser.
       */
      public com.google.protobuf.ByteString
      getDestUserBytes() {
        java.lang.Object ref = destUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          destUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @param value The destUser to set.
       * @return This builder for chaining.
       */
      public Builder setDestUser(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        destUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestUser() {

        destUser_ = getDefaultInstance().getDestUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @param value The bytes for destUser to set.
       * @return This builder for chaining.
       */
      public Builder setDestUserBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        destUser_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 createTime = 6;</code>
       * @return The createTime.
       */
      @java.lang.Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 createTime = 6;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {

        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 createTime = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {

        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.AckMsg.MsgType msgType = 7;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @java.lang.Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.AckMsg.MsgType msgType = 7;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {

        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.AckMsg.MsgType msgType = 7;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public Ack.AckMsg.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        Ack.AckMsg.MsgType result = Ack.AckMsg.MsgType.valueOf(msgType_);
        return result == null ? Ack.AckMsg.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.AckMsg.MsgType msgType = 7;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(Ack.AckMsg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.AckMsg.MsgType msgType = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {

        msgType_ = 0;
        onChanged();
        return this;
      }

      private long ackMsgId_ ;
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>int64 ackMsgId = 8;</code>
       * @return The ackMsgId.
       */
      @java.lang.Override
      public long getAckMsgId() {
        return ackMsgId_;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>int64 ackMsgId = 8;</code>
       * @param value The ackMsgId to set.
       * @return This builder for chaining.
       */
      public Builder setAckMsgId(long value) {

        ackMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>int64 ackMsgId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearAckMsgId() {

        ackMsgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AckMsg)
    }

    // @@protoc_insertion_point(class_scope:AckMsg)
    private static final Ack.AckMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Ack.AckMsg();
    }

    public static Ack.AckMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AckMsg>
            PARSER = new com.google.protobuf.AbstractParser<AckMsg>() {
      @java.lang.Override
      public AckMsg parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new AckMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Ack.AckMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_AckMsg_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_AckMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\tack.proto\"\254\002\n\006AckMsg\022\017\n\007version\030\001 \001(\005\022" +
                    "\n\n\002id\030\002 \001(\003\022\"\n\nfromModule\030\003 \001(\0162\016.AckMsg" +
                    ".Module\022\020\n\010fromUser\030\004 \001(\t\022\020\n\010destUser\030\005 " +
                    "\001(\t\022\022\n\ncreateTime\030\006 \001(\003\022 \n\007msgType\030\007 \001(\016" +
                    "2\017.AckMsg.MsgType\022\020\n\010ackMsgId\030\010 \001(\003\".\n\006M" +
                    "odule\022\n\n\006SERVER\020\000\022\014\n\010TRANSFER\020\001\022\n\n\006CLIEN" +
                    "T\020\002\"E\n\007MsgType\022\r\n\tDELIVERED\020\000\022\010\n\004READ\020\001\022" +
                    "\017\n\013FRIENDAGREE\020\002\022\020\n\014FRIENDDELETE\020\003B\005B\003Ac" +
                    "kb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    });
    internal_static_AckMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_AckMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_AckMsg_descriptor,
            new java.lang.String[] { "Version", "Id", "FromModule", "FromUser", "DestUser", "CreateTime", "MsgType", "AckMsgId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
