// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.zj.protobuf;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zj.protobuf.ChatMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zj.protobuf.ChatMsg.Module fromModule = 3;</code>
     * @return The enum numeric value on the wire for fromModule.
     */
    int getFromModuleValue();
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zj.protobuf.ChatMsg.Module fromModule = 3;</code>
     * @return The fromModule.
     */
    ChatMsg.Module getFromModule();

    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromUser = 4;</code>
     * @return The fromUser.
     */
    String getFromUser();
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromUser = 4;</code>
     * @return The bytes for fromUser.
     */
    com.google.protobuf.ByteString
        getFromUserBytes();

    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destUser = 5;</code>
     * @return The destUser.
     */
    String getDestUser();
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destUser = 5;</code>
     * @return The bytes for destUser.
     */
    com.google.protobuf.ByteString
        getDestUserBytes();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 7;</code>
     * @return The msgBody.
     */
    String getMsgBody();
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 7;</code>
     * @return The bytes for msgBody.
     */
    com.google.protobuf.ByteString
        getMsgBodyBytes();

    /**
     * <code>optional string addition = 32;</code>
     * @return Whether the addition field is set.
     */
    boolean hasAddition();
    /**
     * <code>optional string addition = 32;</code>
     * @return The addition.
     */
    String getAddition();
    /**
     * <code>optional string addition = 32;</code>
     * @return The bytes for addition.
     */
    com.google.protobuf.ByteString
        getAdditionBytes();
  }
  /**
   * Protobuf type {@code com.zj.protobuf.ChatMsg}
   */
  public static final class ChatMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zj.protobuf.ChatMsg)
      ChatMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMsg.newBuilder() to construct.
    private ChatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMsg() {
      fromModule_ = 0;
      fromUser_ = "";
      destUser_ = "";
      msgBody_ = "";
      addition_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              fromModule_ = rawValue;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              fromUser_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              destUser_ = s;
              break;
            }
            case 48: {

              createTime_ = input.readInt64();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              msgBody_ = s;
              break;
            }
            case 258: {
              String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              addition_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Chat.internal_static_com_zj_protobuf_ChatMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Chat.internal_static_com_zj_protobuf_ChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMsg.class, Builder.class);
    }

    /**
     * Protobuf enum {@code com.zj.protobuf.ChatMsg.Module}
     */
    public enum Module
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVER = 0;</code>
       */
      SERVER(0),
      /**
       * <code>TRANSFER = 1;</code>
       */
      TRANSFER(1),
      /**
       * <code>CLIENT = 2;</code>
       */
      CLIENT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SERVER = 0;</code>
       */
      public static final int SERVER_VALUE = 0;
      /**
       * <code>TRANSFER = 1;</code>
       */
      public static final int TRANSFER_VALUE = 1;
      /**
       * <code>CLIENT = 2;</code>
       */
      public static final int CLIENT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Module valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Module forNumber(int value) {
        switch (value) {
          case 0: return SERVER;
          case 1: return TRANSFER;
          case 2: return CLIENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Module> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Module>() {
              public Module findValueByNumber(int number) {
                return Module.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ChatMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Module[] VALUES = values();

      public static Module valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Module(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.zj.protobuf.ChatMsg.Module)
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @Override
    public int getVersion() {
      return version_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int FROMMODULE_FIELD_NUMBER = 3;
    private int fromModule_;
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zj.protobuf.ChatMsg.Module fromModule = 3;</code>
     * @return The enum numeric value on the wire for fromModule.
     */
    @Override public int getFromModuleValue() {
      return fromModule_;
    }
    /**
     * <pre>
     *发送者模块
     * </pre>
     *
     * <code>.com.zj.protobuf.ChatMsg.Module fromModule = 3;</code>
     * @return The fromModule.
     */
    @Override public Module getFromModule() {
      @SuppressWarnings("deprecation")
      Module result = Module.valueOf(fromModule_);
      return result == null ? Module.UNRECOGNIZED : result;
    }

    public static final int FROMUSER_FIELD_NUMBER = 4;
    private volatile Object fromUser_;
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromUser = 4;</code>
     * @return The fromUser.
     */
    @Override
    public String getFromUser() {
      Object ref = fromUser_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>string fromUser = 4;</code>
     * @return The bytes for fromUser.
     */
    @Override
    public com.google.protobuf.ByteString
        getFromUserBytes() {
      Object ref = fromUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTUSER_FIELD_NUMBER = 5;
    private volatile Object destUser_;
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destUser = 5;</code>
     * @return The destUser.
     */
    @Override
    public String getDestUser() {
      Object ref = destUser_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>string destUser = 5;</code>
     * @return The bytes for destUser.
     */
    @Override
    public com.google.protobuf.ByteString
        getDestUserBytes() {
      Object ref = destUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 createTime = 6;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MSGBODY_FIELD_NUMBER = 7;
    private volatile Object msgBody_;
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 7;</code>
     * @return The msgBody.
     */
    @Override
    public String getMsgBody() {
      Object ref = msgBody_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgBody_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息体，json，格式由消息类型决定
     * </pre>
     *
     * <code>string msgBody = 7;</code>
     * @return The bytes for msgBody.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgBodyBytes() {
      Object ref = msgBody_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDITION_FIELD_NUMBER = 32;
    private volatile Object addition_;
    /**
     * <code>optional string addition = 32;</code>
     * @return Whether the addition field is set.
     */
    @Override
    public boolean hasAddition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string addition = 32;</code>
     * @return The addition.
     */
    @Override
    public String getAddition() {
      Object ref = addition_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        addition_ = s;
        return s;
      }
    }
    /**
     * <code>optional string addition = 32;</code>
     * @return The bytes for addition.
     */
    @Override
    public com.google.protobuf.ByteString
        getAdditionBytes() {
      Object ref = addition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        addition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (fromModule_ != Module.SERVER.getNumber()) {
        output.writeEnum(3, fromModule_);
      }
      if (!getFromUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromUser_);
      }
      if (!getDestUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, destUser_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(6, createTime_);
      }
      if (!getMsgBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msgBody_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 32, addition_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (fromModule_ != Module.SERVER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, fromModule_);
      }
      if (!getFromUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromUser_);
      }
      if (!getDestUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, destUser_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
      }
      if (!getMsgBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msgBody_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(32, addition_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatMsg)) {
        return super.equals(obj);
      }
      ChatMsg other = (ChatMsg) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (getId()
          != other.getId()) return false;
      if (fromModule_ != other.fromModule_) return false;
      if (!getFromUser()
          .equals(other.getFromUser())) return false;
      if (!getDestUser()
          .equals(other.getDestUser())) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (!getMsgBody()
          .equals(other.getMsgBody())) return false;
      if (hasAddition() != other.hasAddition()) return false;
      if (hasAddition()) {
        if (!getAddition()
            .equals(other.getAddition())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + FROMMODULE_FIELD_NUMBER;
      hash = (53 * hash) + fromModule_;
      hash = (37 * hash) + FROMUSER_FIELD_NUMBER;
      hash = (53 * hash) + getFromUser().hashCode();
      hash = (37 * hash) + DESTUSER_FIELD_NUMBER;
      hash = (53 * hash) + getDestUser().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
      if (hasAddition()) {
        hash = (37 * hash) + ADDITION_FIELD_NUMBER;
        hash = (53 * hash) + getAddition().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zj.protobuf.ChatMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zj.protobuf.ChatMsg)
        ChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Chat.internal_static_com_zj_protobuf_ChatMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Chat.internal_static_com_zj_protobuf_ChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatMsg.class, Builder.class);
      }

      // Construct using com.zj.protobuf.Chat.ChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        id_ = 0L;

        fromModule_ = 0;

        fromUser_ = "";

        destUser_ = "";

        createTime_ = 0L;

        msgBody_ = "";

        addition_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Chat.internal_static_com_zj_protobuf_ChatMsg_descriptor;
      }

      @Override
      public ChatMsg getDefaultInstanceForType() {
        return ChatMsg.getDefaultInstance();
      }

      @Override
      public ChatMsg build() {
        ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ChatMsg buildPartial() {
        ChatMsg result = new ChatMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.version_ = version_;
        result.id_ = id_;
        result.fromModule_ = fromModule_;
        result.fromUser_ = fromUser_;
        result.destUser_ = destUser_;
        result.createTime_ = createTime_;
        result.msgBody_ = msgBody_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.addition_ = addition_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatMsg) {
          return mergeFrom((ChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatMsg other) {
        if (other == ChatMsg.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.fromModule_ != 0) {
          setFromModuleValue(other.getFromModuleValue());
        }
        if (!other.getFromUser().isEmpty()) {
          fromUser_ = other.fromUser_;
          onChanged();
        }
        if (!other.getDestUser().isEmpty()) {
          destUser_ = other.destUser_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (!other.getMsgBody().isEmpty()) {
          msgBody_ = other.msgBody_;
          onChanged();
        }
        if (other.hasAddition()) {
          bitField0_ |= 0x00000001;
          addition_ = other.addition_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChatMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>int32 version = 1;</code>
       * @return The version.
       */
      @Override
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>int32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>int32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int64 id = 2;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int64 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int64 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int fromModule_ = 0;
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zj.protobuf.ChatMsg.Module fromModule = 3;</code>
       * @return The enum numeric value on the wire for fromModule.
       */
      @Override public int getFromModuleValue() {
        return fromModule_;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zj.protobuf.ChatMsg.Module fromModule = 3;</code>
       * @param value The enum numeric value on the wire for fromModule to set.
       * @return This builder for chaining.
       */
      public Builder setFromModuleValue(int value) {
        
        fromModule_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zj.protobuf.ChatMsg.Module fromModule = 3;</code>
       * @return The fromModule.
       */
      @Override
      public Module getFromModule() {
        @SuppressWarnings("deprecation")
        Module result = Module.valueOf(fromModule_);
        return result == null ? Module.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zj.protobuf.ChatMsg.Module fromModule = 3;</code>
       * @param value The fromModule to set.
       * @return This builder for chaining.
       */
      public Builder setFromModule(Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fromModule_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者模块
       * </pre>
       *
       * <code>.com.zj.protobuf.ChatMsg.Module fromModule = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromModule() {
        
        fromModule_ = 0;
        onChanged();
        return this;
      }

      private Object fromUser_ = "";
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @return The fromUser.
       */
      public String getFromUser() {
        Object ref = fromUser_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromUser_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @return The bytes for fromUser.
       */
      public com.google.protobuf.ByteString
          getFromUserBytes() {
        Object ref = fromUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @param value The fromUser to set.
       * @return This builder for chaining.
       */
      public Builder setFromUser(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUser() {
        
        fromUser_ = getDefaultInstance().getFromUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>string fromUser = 4;</code>
       * @param value The bytes for fromUser to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromUser_ = value;
        onChanged();
        return this;
      }

      private Object destUser_ = "";
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @return The destUser.
       */
      public String getDestUser() {
        Object ref = destUser_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          destUser_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @return The bytes for destUser.
       */
      public com.google.protobuf.ByteString
          getDestUserBytes() {
        Object ref = destUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          destUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @param value The destUser to set.
       * @return This builder for chaining.
       */
      public Builder setDestUser(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestUser() {
        
        destUser_ = getDefaultInstance().getDestUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>string destUser = 5;</code>
       * @param value The bytes for destUser to set.
       * @return This builder for chaining.
       */
      public Builder setDestUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destUser_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 createTime = 6;</code>
       * @return The createTime.
       */
      @Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 createTime = 6;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 createTime = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private Object msgBody_ = "";
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 7;</code>
       * @return The msgBody.
       */
      public String getMsgBody() {
        Object ref = msgBody_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgBody_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 7;</code>
       * @return The bytes for msgBody.
       */
      public com.google.protobuf.ByteString
          getMsgBodyBytes() {
        Object ref = msgBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 7;</code>
       * @param value The msgBody to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgBody() {
        
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体，json，格式由消息类型决定
       * </pre>
       *
       * <code>string msgBody = 7;</code>
       * @param value The bytes for msgBody to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgBody_ = value;
        onChanged();
        return this;
      }

      private Object addition_ = "";
      /**
       * <code>optional string addition = 32;</code>
       * @return Whether the addition field is set.
       */
      public boolean hasAddition() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string addition = 32;</code>
       * @return The addition.
       */
      public String getAddition() {
        Object ref = addition_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          addition_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string addition = 32;</code>
       * @return The bytes for addition.
       */
      public com.google.protobuf.ByteString
          getAdditionBytes() {
        Object ref = addition_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          addition_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string addition = 32;</code>
       * @param value The addition to set.
       * @return This builder for chaining.
       */
      public Builder setAddition(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        addition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string addition = 32;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddition() {
        bitField0_ = (bitField0_ & ~0x00000001);
        addition_ = getDefaultInstance().getAddition();
        onChanged();
        return this;
      }
      /**
       * <code>optional string addition = 32;</code>
       * @param value The bytes for addition to set.
       * @return This builder for chaining.
       */
      public Builder setAdditionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        addition_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zj.protobuf.ChatMsg)
    }

    // @@protoc_insertion_point(class_scope:com.zj.protobuf.ChatMsg)
    private static final ChatMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatMsg();
    }

    public static ChatMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMsg>
        PARSER = new com.google.protobuf.AbstractParser<ChatMsg>() {
      @Override
      public ChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public ChatMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zj_protobuf_ChatMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zj_protobuf_ChatMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nchat.proto\022\017com.zj.protobuf\"\370\001\n\007ChatMs" +
      "g\022\017\n\007version\030\001 \001(\005\022\n\n\002id\030\002 \001(\003\0223\n\nfromMo" +
      "dule\030\003 \001(\0162\037.com.zj.protobuf.ChatMsg.Mod" +
      "ule\022\020\n\010fromUser\030\004 \001(\t\022\020\n\010destUser\030\005 \001(\t\022" +
      "\022\n\ncreateTime\030\006 \001(\003\022\017\n\007msgBody\030\007 \001(\t\022\025\n\010" +
      "addition\030  \001(\tH\000\210\001\001\".\n\006Module\022\n\n\006SERVER\020" +
      "\000\022\014\n\010TRANSFER\020\001\022\n\n\006CLIENT\020\002B\013\n\t_addition" +
      "B\006B\004Chatb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zj_protobuf_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zj_protobuf_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zj_protobuf_ChatMsg_descriptor,
        new String[] { "Version", "Id", "FromModule", "FromUser", "DestUser", "CreateTime", "MsgBody", "Addition", "Addition", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
